name       : gcr-4
version    : 4.1.0
release    : 4
source     :
    - https://download.gnome.org/sources/gcr/4.1/gcr-4.1.0.tar.xz : 9ceaad29284ba919b9216e2888c18ec67240c2c93b3a4856bc5488bbc1f3a383
license    : GPL-3.0-or-later
component  : desktop.gnome.core
summary    : The Gcr package contains libraries used for displaying certificates and accessing key stores. It also provides the viewer for crypto files on the GNOME Desktop.
description: |
    The Gcr package contains libraries used for displaying certificates and accessing key stores. It also provides the viewer for crypto files on the GNOME Desktop.
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libsecret-1)
    - pkgconfig(p11-kit-1)
    - libgcrypt-devel
    - gnupg
    - openssh
    - vala
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
