name       : gcr-4
version    : 4.0.0
release    : 3
source     :
    - https://download.gnome.org/sources/gcr/4.0/gcr-4.0.0.tar.xz : c45855924f0ee7bab43e2dd38bfafd2ac815c6e9864341c0161e171173dcec7c
license    : GPL-3.0-or-later
component  : desktop.gnome.core
summary    : The Gcr package contains libraries used for displaying certificates and accessing key stores. It also provides the viewer for crypto files on the GNOME Desktop.
description: |
    The Gcr package contains libraries used for displaying certificates and accessing key stores. It also provides the viewer for crypto files on the GNOME Desktop.
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libsecret-1)
    - pkgconfig(p11-kit-1)
    - libgcrypt-devel
    - gnupg
    - openssh
    - vala
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
